# Generated by Django 5.2.7 on 2025-10-27 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_date',
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
